### ISSUE TITLE
Blink Nodes and Cameras

### ISSUE THREAD

**Issue by PaulStraten** [Panda88CO/udi-Blink#5]
I have 4 cameras on my BLINK system but do not see them under my nodes.
Please advise.
See screenshot attached.
![Blink 4 Cameras](https://user-images.githubusercontent.com/79529512/213022012-88180cfc-d57e-4fee-8ec2-6e745b055ca4.jpg)

**Comment by Panda88CO** [comment]
Did you setup the sync unit name in the configuration - if yes - name may be too long to handle in the blink API
A log would help

**Comment by PaulStraten** [comment]
No sir, I did not. I didn’t understand what that means exactly.

Can you explain or shall I just send you the log in a reply email first?

And thank you for being so responsive! Very refreshing 😊

Thank you,

Paul Straten
***@***.***

**Comment by PaulStraten** [comment]
As requested

Thank you,

Paul Straten
***@***.***

From: Paul Straten
Sent: Tuesday, January 17, 2023 4:55 PM
To: Panda88CO/udi-Blink ***@***.***>
Subject: RE: [Panda88CO/udi-Blink] Blink Nodes and Cameras (Issue #5)

No sir, I did not. I didn’t understand what that means exactly.

Can you explain or shall I just send you the log in a reply email first?

And thank you for being so responsive! Very refreshing 😊

Thank you,

Paul Straten
***@***.******@***.***>

**Comment by Panda88CO** [comment]
You need to press configuration option and set username and password from the app - as well as the name of your sync unit (this is optional)

**Comment by PaulStraten** [comment]
Also, did you get the screenshot I included?

Thank you,

Paul Straten
***@***.***

**Comment by Panda88CO** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by PaulStraten** [comment]
Yes, I set the username and password in the PG3 nodeserver application

Thank you,

Paul Straten
***@***.***

**Comment by Panda88CO** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by PaulStraten** [comment]
????

Thank you,

Paul Straten
***@***.***

**Comment by PaulStraten** [comment]
I inserted USERNAME and PASSWORD in the nodeserver app on PG3 already.

Thank you,

Paul Straten
***@***.***

From: Paul Straten
Sent: Tuesday, January 17, 2023 4:55 PM
To: Panda88CO/udi-Blink ***@***.***>
Subject: RE: [Panda88CO/udi-Blink] Blink Nodes and Cameras (Issue #5)

No sir, I did not. I didn’t understand what that means exactly.

Can you explain or shall I just send you the log in a reply email first?

And thank you for being so responsive! Very refreshing 😊

Thank you,

Paul Straten
***@***.******@***.***>

**Comment by Panda88CO** [comment]
email - does not work well
I think you either need to enter you sync unit name (if you a have a sync unit)- or clear the field under configuration. 
I did not get your log file - it may be easier to use the ISY forum for this as interface is easier to use

**Comment by PaulStraten** [comment]
Let me try sending you the file again

Thank you,

Paul Straten
***@***.***

**Comment by PaulStraten** [comment]
[Blink_1-17-2023_45900-PM.zip](https://github.com/Panda88CO/udi-Blink/files/10440063/Blink_1-17-2023_45900-PM.zip)
how about this? log file?

**Comment by PaulStraten** [comment]
i just sent you a zipped file of the logfile

**Comment by PaulStraten** [comment]
I don’t know what you mean regarding “sync unit name”?

**Comment by Panda88CO** [comment]
If you use a sync unit with the system - you gave it a name in the app - it is that name

**Comment by PaulStraten** [comment]
I cleared out sync units field in the configuration and still only see 2 nodes (screenshot I sent you earlier)

**Comment by Panda88CO** [comment]
You need to delete the 2nd node and re start - or possibly delete node server and try to install again

**Comment by PaulStraten** [comment]
When I delete the second node (called BLINKSETUP) and restart it, it adds it back automaticlly

**Comment by PaulStraten** [comment]
I will try to delete and re-install

I will only add:
1. username
2. passwword
3. leave sync unit name blank

sound okay?

**Comment by PaulStraten** [comment]
I just read up on the BLINK website, and I do not have a sync module, therefore I shouldnt have a sync name, correct?

And it still isnt showing any nodes - just 1 now since I re-installed it

**Comment by PaulStraten** [comment]
Sorry, I do not have sync module so I should NOT have a sync unit name, correct?

**Comment by PaulStraten** [comment]
log attached - it is successfully logging into my account from what this shows but not getting certain data?

**Comment by PaulStraten** [comment]
[Blink_1-17-2023_53539-PM.zip](https://github.com/Panda88CO/udi-Blink/files/10440397/Blink_1-17-2023_53539-PM.zip)

**Comment by PaulStraten** [comment]
![configuration](https://user-images.githubusercontent.com/79529512/213040529-adbbacc9-f05a-4d39-8dc6-24ba0508d4a5.jpg)

**Comment by Panda88CO** [comment]
My guess is you cannot have ' (special characters) in the camera name - I can see it finds 3 cameras but stops after that - I had a similar issue for anther user - it worked after renaming the camears.  If this does not work can you generate another log file but set level to debug

**Comment by PaulStraten** [comment]
2 of the cameras did NOT have ANY special characters. 2 of them had an apostrophe.

I renamed them to:
  Jackie Playroom
  Jackie Bedroom
  Garage (original name)
  Family Room (original name)

I then "restarted" the nodeserver. Nothing changed.



Attached is new log.
[Blink_1-17-2023_72224-PM.zip](https://github.com/Panda88CO/udi-Blink/files/10440997/Blink_1-17-2023_72224-PM.zip)

**Comment by Panda88CO** [comment]
Did you ever create a thumbnail - take a picture that shows in the app - It complains it cannot find a thumbnail - If not just take a picture with each of the cameras and try again - maybe reinstall is a good thing 
I am sorry I cannot help more, but I am using an API to address the camera and it is the API complaining

**Comment by PaulStraten** [comment]
I took a picture with each camera again
I uninstalled nodeserver again and re-installed it
No luck - not sure what else to try

**Comment by PaulStraten** [comment]
Seems like the more I did, the worse it got ?

**Comment by Panda88CO** [comment]
Can you enable debug in the log and send it to me after restarting
I wonder if it is related to you not having a sync unit - I have not tried without having one activated (but did try with cloud storage enabled)
BTW - what cameras do you have

**Comment by PaulStraten** [comment]
attached is log - and thank you for sticking with this!

[debug.log](https://github.com/Panda88CO/udi-Blink/files/10447317/debug.log)

**Comment by Panda88CO** [comment]
yes - you need to enter this code in the AUTH_KEY field  under config - once done and if it does not fix it send another log 
I would erase this post/picture with the code - I think the code is time limited so you may need to generate a new one 
Thanks

**Comment by PaulStraten** [comment]
I restarted (ay 10:59 am) after adding that code (which BLINK continues to text me every 45-50 minutes) and it doesnt see the nodes yet. Log attached.
[Blink_1-18-2023_105955-AM.zip](https://github.com/Panda88CO/udi-Blink/files/10448798/Blink_1-18-2023_105955-AM.zip)

**Comment by Panda88CO** [comment]
I may have a bug - can you try to write NONE in the sync_unit field 
I have not been able to test a system without a sync unit before

**Comment by PaulStraten** [comment]
I thought about doing that late last night but was already in bed! :-)
Stand by.

**Comment by PaulStraten** [comment]
:-(
Restarted at 11:33 am
Log attaached.
[Blink_1-18-2023_113425-AM.zip](https://github.com/Panda88CO/udi-Blink/files/10449067/Blink_1-18-2023_113425-AM.zip)

**Comment by Panda88CO** [comment]
The issue is you had something there before so it is read as an empty character - and not nothing - my code did not handle this - but it does include the option to add NONE

**Comment by PaulStraten** [comment]
![configuration](https://user-images.githubusercontent.com/79529512/213254005-55306b9f-65e6-481e-a15c-3cdcb92ca3ff.jpg)

Just an FYI

**Comment by Panda88CO** [comment]
Looks correct - it is the API complaining
What cameras are you using?  
Maybe try to delete and reinstall once more - maybe in a different polisy slot

**Comment by PaulStraten** [comment]
I have 4 of these cameras - see attached.
I will try and re-install in another slot.
![front](https://user-images.githubusercontent.com/79529512/213266053-06de6abd-f597-4a3a-97eb-11d5fa847930.jpg)
![back](https://user-images.githubusercontent.com/79529512/213266084-515a85be-ae6a-474d-b42d-5dc87af5c472.jpg)

**Comment by PaulStraten** [comment]
Still no luck after deleting the re-installing in a brand new socket (11)

restarted at 12:44

[Blink_1-18-2023_124457-PM.zip](https://github.com/Panda88CO/udi-Blink/files/10449600/Blink_1-18-2023_124457-PM.zip)

**Comment by PaulStraten** [comment]
I just saw in my app that the cameras are also lined to a "SYSTEM" field of some sort. 
Could this be causing issue?
My system name is "Shadywood"
See screenshot my app identifying such.
![system](https://user-images.githubusercontent.com/79529512/213268121-0c123d51-6e4e-466a-9ed9-15a927975ee7.jpg)

**Comment by Panda88CO** [comment]
That is the name of your sync unit – try to add this in stead of NONE Sent from Mail for Windows From: PaulStratenSent: Wednesday, January 18, 2023 10:48 AMTo: Panda88CO/udi-BlinkCc: Panda88CO; CommentSubject: Re: [Panda88CO/udi-Blink] Blink Nodes and Cameras (Issue #5) I just saw in my app that the cameras are also lined to a "SYSTEM" field of some sort.Could this be causing issue?My system name is "Shadywood"See screenshot my app identifying such.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by PaulStraten** [comment]
I tried that yesterday, but did it again anyway.
No luck.
See attached.
Restarted at 1:05
[Blink_1-18-2023_10619-PM.zip](https://github.com/Panda88CO/udi-Blink/files/10449814/Blink_1-18-2023_10619-PM.zip)
![configuration](https://user-images.githubusercontent.com/79529512/213271928-82b2c190-ac8b-492b-a801-4bb958c39ef7.jpg)
![another](https://user-images.githubusercontent.com/79529512/213271961-72f2e566-b592-4d21-977a-5f89ebe8dd81.jpg)

**Comment by Panda88CO** [comment]
Let me try to access your system later today - I may need you to provide the auth code - I'll erase after I get access - I need to add some more debug information to see if I can understand what is happening

**Comment by PaulStraten** [comment]
Sounds good.

Username is: paul@straten.com
Password is: Paul123*
System name is: Shadywood 

* I will put a piece of paper in front of each camera to maintain video anonymity - so make yourself at home :-)

It may require that 2-step verification so I will text you that if it texts me (that will mean you are in the system and it is requesting access) NOTE: I would like to turn that off but don't know how, do you? Also, I may not have access to a PC tonight so that is why I said "text you" - if you want to share your cell phone with me? Mine is (817) 366-7999. Then again, maybe that last code that has been entered in there will still work - it hasn't pinged me since this morning requesting another one.

Let me know what else you need. And again, thank you for sticking with it! Admirable.
